name: wxedge for Home Assistant
version: 5.6.3
slug: wxedge
description: 利用空闲机器创收
url: https://github.com/jnukylin/hassio-addons/tree/master/wxedge
image: onething1/wxedge
advanced: true
arch:
  - aarch64
  - amd64
hassio_api: true
hassio_role: manager
host_network: true
ingress: true
ingress_port: 18888
init: false
map:
  - config:rw
  - media:rw
  - share:rw
  - ssl
panel_icon: mdi:cloud
panel_title: 网心云
ports:
  18888/tcp: null
startup: services
privileged:
- SYS_ADMIN
